# This workflow builds the Go project for multiple platforms and creates a release
name: Go Multi-Platform Build and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [linux]
        arch: [amd64] # Intel (amd64) and Apple M-series (arm64)

    steps:
    # Step 1: Check out the code
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up Go environment
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.2'

    # Step 3: Cache Go modules
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    # Step 4: Install dependencies
    - name: Install dependencies
      run: go mod tidy

    # Step 5.1: Generate release tag
    - name: Generate release tag
      id: generate_tag
      run: |
        MAJOR=1
        MINOR=0
        echo "RELEASE_TAG=v${MAJOR}.${MINOR}" >> $GITHUB_ENV

    # Step 5.2: Set up CGO environment for cross-compilation
    - name: Set environment for CGO
      run: |
        if [ "${{ matrix.platform }}" == "windows" ]; then
          export CC=x86_64-w64-mingw32-gcc
        elif [ "${{ matrix.platform }}" == "darwin" ]; then
          export CC=o64-clang
        elif [ "${{ matrix.platform }}" == "linux" ]; then
          export CC=gcc
        fi
        export CGO_ENABLED=1
        echo "Environment for CGO set."

    # Step 6: Build the main application for each platform
    - name: Build main application
      run: |
        mkdir -p build/${{ matrix.platform }}-${{ matrix.arch }}
        GOOS=${{ matrix.platform }} GOARCH=${{ matrix.arch }} go build -o build/${{ matrix.platform }}-${{ matrix.arch }}/notification-system main.go

    # Step 7: Build plugins for each platform
    - name: Build plugins
      run: |
        mkdir -p build/${{ matrix.platform }}-${{ matrix.arch }}/plugins
        GOOS=${{ matrix.platform }} GOARCH=${{ matrix.arch }} go build -buildmode=plugin -o build/${{ matrix.platform }}-${{ matrix.arch }}/plugins/telegram.so plugins/telegram/telegram.go
        GOOS=${{ matrix.platform }} GOARCH=${{ matrix.arch }} go build -buildmode=plugin -o build/${{ matrix.platform }}-${{ matrix.arch }}/plugins/discord.so plugins/discord/discord.go
        GOOS=${{ matrix.platform }} GOARCH=${{ matrix.arch }} go build -buildmode=plugin -o build/${{ matrix.platform }}-${{ matrix.arch }}/plugins/slack.so plugins/slack/slack.go
        GOOS=${{ matrix.platform }} GOARCH=${{ matrix.arch }} go build -buildmode=plugin -o build/${{ matrix.platform }}-${{ matrix.arch }}/plugins/teams.so plugins/teams/teams.go
        GOOS=${{ matrix.platform }} GOARCH=${{ matrix.arch }} go build -buildmode=plugin -o build/${{ matrix.platform }}-${{ matrix.arch }}/plugins/webhook.so plugins/webhook/webhook.go
        GOOS=${{ matrix.platform }} GOARCH=${{ matrix.arch }} go build -buildmode=plugin -o build/${{ matrix.platform }}-${{ matrix.arch }}/plugins/smtp.so plugins/smtp/smtp.go
        GOOS=${{ matrix.platform }} GOARCH=${{ matrix.arch }} go build -buildmode=plugin -o build/${{ matrix.platform }}-${{ matrix.arch }}/plugins/push.so plugins/push/push.go
        GOOS=${{ matrix.platform }} GOARCH=${{ matrix.arch }} go build -buildmode=plugin -o build/${{ matrix.platform }}-${{ matrix.arch }}/plugins/sms.so plugins/sms/sms.go
        GOOS=${{ matrix.platform }} GOARCH=${{ matrix.arch }} go build -buildmode=plugin -o build/${{ matrix.platform }}-${{ matrix.arch }}/plugins/signal.so plugins/signal/signal.go
        GOOS=${{ matrix.platform }} GOARCH=${{ matrix.arch }} go build -buildmode=plugin -o build/${{ matrix.platform }}-${{ matrix.arch }}/plugins/rocketchat.so plugins/rocketchat/rocketchat.go

    # Step 8: Archive the build folder for each platform
    - name: Archive build folder
      run: zip -r dynamic-notification-system-${{ env.RELEASE_TAG }}-${{ matrix.platform }}-${{ matrix.arch }}.zip build/${{ matrix.platform }}-${{ matrix.arch }}

    # Step 9: Upload artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dynamic-notification-system-${{ env.RELEASE_TAG }}-${{ matrix.platform }}-${{ matrix.arch }}
        path: dynamic-notification-system-${{ env.RELEASE_TAG }}-${{ matrix.platform }}-${{ matrix.arch }}.zip

  release:
    needs:
      - build
    runs-on: ubuntu-latest

    steps:
    # Step 1: Download artifacts
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        path: artifacts

    # Step 2: Create GitHub Release
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: artifacts/**/*.zip
        tag_name: ${{ env.RELEASE_TAG }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
