name: test Build and Release

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-tags: true

    - name: Generate release tag
      id: generate_tag
      run: |
        chmod +x bump-version.sh
        RELEASE_TAG=$(./bump-version.sh)
        echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV
        echo $RELEASE_TAG